export const UPDATE_RANDOM_JOKE = 'UPDATE_RANDOM_JOKE';
export const UPDATE_RANDOM_CATEGORIE_JOKE = 'UPDATE_RANDOM_CATEGORIE_JOKE';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'